apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apples.example.com #spec.names.plural+"."+spec.group
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: apples
    singular: apple
    kind: Apple
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}  # Enable status subresource
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
